spring.application.name=payment-service

# Prefix global de nos endpoints
spring.mvc.servlet.path=/api

# Connexion  PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/payment_db
spring.datasource.username=payment_user
spring.datasource.password=${PAYMENT_DB_PASSWORD}

# Configuration JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

payment.monitoring.pending-threshold-minutes=5
payment.monitoring.scan-interval-ms=60000

payment.security.jwt.secret=${JWT_SECRET}
payment.security.jwt.expiration-seconds=3600
