spring.application.name=payment-service

# Prefix global de nos endpoints
spring.mvc.servlet.path=/api

# Connexion  PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/payment_db
spring.datasource.username=payment_user
spring.datasource.password=${PAYMENT_DB_PASSWORD}

# Configuration JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

payment.monitoring.pending-threshold-minutes=5
payment.monitoring.scan-interval-ms=60000

payment.security.jwt.secret=${JWT_SECRET}
payment.security.jwt.expiration-seconds=3600

# ==========================================
# LOGGING CONFIGURATION
# ==========================================

# Nom du fichier de logs
logging.file.name=${PAYMENT_LOG_FILE:logs/payment-service.log}

# Niveau global
logging.level.root=INFO

# Niveau des classes de notre application
logging.level.com.bankpaymentmonitor.paymentservice=INFO

# Taille maximale d'un fichier avant rotation
logging.logback.rollingpolicy.max-file-size=10MB

# Nombre de jours de conservation
logging.logback.rollingpolicy.max-history=30

# Limite totale des archives
logging.logback.rollingpolicy.total-size-cap=1GB

# Format des logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [correlationId=%X{correlationId:-N/A}] %logger{36} - %msg%n
