CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          reference VARCHAR(100) NOT NULL,
                          source_system VARCHAR(50) NOT NULL,
                          source_payment_reference VARCHAR(100) NOT NULL,
                          branch_code VARCHAR(30) NOT NULL,

                          amount NUMERIC(19, 2) NOT NULL,
                          currency VARCHAR(3) NOT NULL,
                          status VARCHAR(20) NOT NULL,

                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,

                          CONSTRAINT uk_payment_reference
                              UNIQUE (reference),

                          CONSTRAINT uk_payment_source_reference
                              UNIQUE (source_system, source_payment_reference)
);