CREATE TABLE payment_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_reference VARCHAR(100) NOT NULL,

    branch_code VARCHAR(30) NOT NULL,

    alert_type VARCHAR(50) NOT NULL,

    detected_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_payment_alert
        UNIQUE (payment_reference, alert_type)
);